apiVersion: v1
kind: PersistentVolume
metadata:
  name: alcanza-wp
  namespace: alcanzapoesia
  labels:
    project: alcanzapoesia
spec:
  capacity:
    storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain