apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alcanza-wp
  namespace: alcanzapoesia
  labels:
    project: alcanzapoesia
spec:
  resources:
    requests:
      storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: alcanza-wp
